### ISSUE TITLE
database backup trying to use AWS secrets rather than IAM when accesskey and secretkey are blank

### ISSUE THREAD

**Issue by jwalters-gpsw** [deis/postgres#192]
I have IAM setup and have confirmed it works in the deis  namespace by running up generic ubuntu and accessing the bucket successfully. However the database log is showing this:

```
Performing an initial backup...
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2017-04-13T21:05:13.346499-00 pid=111
wal_e.main   ERROR    MSG: AWS Access Key credential is required but not provided
        HINT: Pass "--aws-access-key-id" or set the environment variable "AWS_ACCESS_KEY_ID".
        STRUCTURED: time=2017-04-13T21:05:13.346858-00 pid=111
```

My values config snippets are:

```
global:
  # Set the storage backend
  #
  # Valid values are:
  # - s3: Store persistent data in AWS S3 (configure in S3 section)
  # - azure: Store persistent data in Azure's object storage
  # - gcs: Store persistent data in Google Cloud Storage
  # - minio: Store persistent data on in-cluster Minio server
  storage: s3
.
.
.
  database_location: "on-cluster"
.
.
.
s3:
  # Your AWS access key. Leave it empty if you want to use IAM credentials.
  accesskey: ""
  # Your AWS secret key. Leave it empty if you want to use IAM credentials.
  secretkey: ""
  # Any S3 region
  region: "us-west-2"
  # Your buckets.
  registry_bucket: "tectonic-deis-registry"
  database_bucket: "tectonic-deis-database"
  builder_bucket: "tectonic-deis-builder"
```

This is with chart 2.13 (assuming this is the latest).
