### ISSUE TITLE
Liveness check failing with 'Unrecognized input header'

### ISSUE THREAD

**Issue by slack** [deis/postgres#43]
v2-beta:

```
NAMESPACE   FIRSTSEEN   LASTSEEN   COUNT     NAME                  KIND      SUBOBJECT                        REASON      SOURCE                                              MESSAGE
deis        1d          0s         16822     deis-database-z0j7q   Pod       spec.containers{deis-database}   Unhealthy   {kubelet ip-10-0-0-62.us-west-2.compute.internal}   Liveness probe errored: Unrecognized input header
```

```
    livenessProbe:
      exec:
        command:
        - is_master
      initialDelaySeconds: 30
      timeoutSeconds: 1
```
